### ISSUE TITLE
Just FYI, a few issues with the kitchen sink on the web site

### ISSUE THREAD

**Issue by rex** [reapp/reapp#1]
Sorry to jump in and bug you guys, as there is a high probability that you have already identified these issues. 

The first few items in the iPhone kitchen sink worked fine, but clicking on `Modals` did not work, nor did subsequent clicks on other items. Screenshot of console output:

![screenshot 2015-01-28 13 32 19](https://cloud.githubusercontent.com/assets/4247754/5945183/4e45874c-a6f2-11e4-91d1-a2535a8a67af.png)

Please let me know if further information would help!

**Comment by natew** [comment]
First issue!

Looks like something with how we are embedding it. You can access it directly at [kitchen.reapp.io](http://kitchen.reapp.io). We are pre-launch still though, I will check into it further.

What browser are you using?

**Comment by rex** [comment]
I'll admit to being a little excited to be the guy opening the first issue on this going-to-hit-big repo :) 

I am using Chrome, latest version. Which is, at the time of this comment, `40.0.2214.93 (64-bit)`. 

![screenshot 2015-01-28 18 01 39](https://cloud.githubusercontent.com/assets/4247754/5949834/c66336b4-a717-11e4-97bb-74a595cc4732.png)

**Comment by natew** [comment]
Thanks for this ticket again, I'm going to close it because I've iterated a bunch on the Kitchen Sink, but in general there are a number of bugs with that. Feel free to open individual ones [on the repo](https://github.com/reapp/kitchen-sink) though, though I understand if you don't.
