### ISSUE TITLE
problem with install and/or starting

### ISSUE THREAD

**Issue by brw31415** [reapp/reapp#102]
I had a problem running the first time

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in /home/brw314/reapp/te
st                                                                                                 
 @ multi main                                                                                      
                                                                                                   
ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack/hot/only-dev-server' in /home/brw314/reapp/
test                                                                                               
 @ multi main                                                                                      
                                                                                                   
ERROR in multi main
Module not found: Error: Cannot resolve module 'babel-loader' in /home/brw314/reapp/test           
 @ multi main                                                                                      
webpack: bundle is now VALID.                                                                      
                                                                                                   
Build took 0.927 seconds

**Comment by pinturic** [comment]
It seams not all the dependencies have beeb installed correctly. 
Can you please try launching: 

"npm install" 

and see if it helps? Otherwise please write the results here again.

**Comment by brw31415** [comment]
thanks, i will try in a bit, but i am pretty new to npm and find this
happens more often than not.   The article in this link might be relevant
http://www.sitepoint.com/solve-global-npm-module-dependency-problem/

**Comment by brw31415** [comment]
I'm doing this on two seperate instances, one on a debian jesse, and
another on ubuntu 14.40

On one computer (debian) everything went (no error output) fine until , but
when i tried

reapp run, this came out:

**The only big change you need is to move your layout.html to
assets/web/index.html. But we've
made some improvements to the layouts, so we recommend creating a new
reapp project and
copying over the /assets folder.**brw314@Lydia:~/reapp$ ls
bin  lib  LICENSE  package.json  README.md  test  test3  UPGRADE.md
brw314@Lydia:~/reapp$ reapp run
No reapp application found, ensure reapp: "0.8" is set in
package.json.


this is the package.json file:


{
  "name": "reapp",
  "version": "0.8.28",
  "description": "a server, build system, and helpers for react apps",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/reapp/reapp.git"
  },
  "author": "Nate Wienert",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/reapp/reapp/issues"
  },
  "homepage": "https://github.com/reapp/reapp",
  "dependencies": {
    "colors": "~1.0.3",
    "commander": "^2.6.0",
    "es6-promise": "^2.0.1",
    "mkdirp": "^0.5.0",
    "ncp": "~1.0.1",
    "reapp-object-assign": "^1.0.0",
    "reapp-pack": "^1.3.19",
    "reapp-server": "^1.0.1",
    "replace": "~0.3.0",
    "rimraf": "~2.2.8"
  },
  "bin": {
    "reapp": "./bin/reapp",
    "reapp-new": "./bin/reapp-new",
    "reapp-build": "./bin/reapp-build",
    "reapp-run": "./bin/reapp-run",
    "reapp-debug": "./bin/reapp-debug",
    "reapp-config": "./bin/reapp-config"
  }
}


the ubuntu instance yielded this:


Running npm install...

 Error
{ [Error: Command failed: /bin/sh -c npm install
npm WARN package.json test3@1.0.0 No repository field.
npm WARN package.json test3@1.0.0 No license field.
npm WARN peerDependencies The peer dependency fbjs@^0.2.1 included
from react-tap-event-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill
the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to
depend on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@^0.14.0-0
included from react-tap-event-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill
the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to
depend on it explicitly.
npm WARN peerDependencies The peer dependency react@^0.14.3 included
from react-dom will no
npm WARN peerDependencies longer be automatically installed to fulfill
the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to
depend on it explicitly.
npm WARN peerDependencies The peer dependency react@0.14.x included
from reapp-ui will no
npm WARN peerDependencies longer be automatically installed to fulfill
the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to
depend on it explicitly.
npm WARN deprecated react-tools@0.13.2: react-tools is deprecated. For
more information, visit https://fb.me/react-tools-deprecated
npm WARN optional dep failed, continuing fsevents@1.0.5
npm WARN engine stacktrace-parser@0.1.1: wanted: {"node":"~0.10"}
(current: {"node":"4.1.1","npm":"2.14.4"})
npm WARN optional dep failed, continuing fsevents@1.0.5
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.1.1/bin/node"
"/home/ubuntu/.nvm/versions/node/v4.1.1/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@0.14.3 does not satisfy its
siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer omniscient@3.3.0 wants react@>=0.12.0 ||
>=0.14.0-alpha
npm ERR! peerinvalid Peer react-router@0.13.5 wants react@0.13.x||0.14.x
npm ERR! peerinvalid Peer reapp-routes@0.10.12 wants react@0.13.x
npm ERR! peerinvalid Peer reapp-ui@0.12.70 wants react@0.14.x

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/reapp/reapp/test3/npm-debug.log
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c npm install' }

**Comment by fabulous-fab14** [comment]
I am having the same problem as @brw31415 and I am running Ubuntu 14.40 as well
I installed `reapp` globally and create the app. I also exectued `npm install` once more after the creation and I still have the same errors as @brw31415 

here is my error log:

     ERROR in multi main
     Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in /home/fabio/Documents/App
     @ multi main

    ERROR in multi main
    Module not found: Error: Cannot resolve module 'webpack/hot/only-dev-server' in /home/fabio/Documents/App
     @ multi main

    ERROR in multi main
    Module not found: Error: Cannot resolve module 'babel-loader' in /home/fabio/Documents/App
    @ multi main

**Comment by arnaudmolo** [comment]
Had the same issue on Yosemite
Fixed it by installing reapp localy `npm i reapp`

**Comment by ryd0rz** [comment]
Resolved with new version of reapp.

Do:
npm uninstall -g reapp
npm install -g reapp
reapp new test-reapp
cd test-reapp
reapp run
