### ISSUE TITLE
Uncaught Error: Invariant Violation: Unable to find <Route name="tabs">

### ISSUE THREAD

**Issue by GloverDonovan** [reapp/reapp#11]
Hello,

I received the following error while testing the Kitchen Sink interface.

```
x Uncaught Error: Invariant Violation: Unable to find <Route name="tabs">
3 invariant.js:49 Uncaught Error: Invariant Violation: Unable to find <Route name="tabs">
```

Unfortunately, I am unable to replicate it once more. Hopefully the error message is verbose enough!

**Comment by natew** [comment]
I pushed a couple broken builds up last night :laughing: so that may be it. Thanks for the report though! I'll close for now.
