### ISSUE TITLE
Problem starting app

### ISSUE THREAD

**Issue by funerr** [reapp/reapp#112]
I can't get my application to start, any ideas?
`D:\Development\test-reapp>reapp new test-reapp` then `D:\Development\test-reapp>cd test-reapp` then:
```
D:\Development\test-reapp\test-reapp>reapp run .
Couldn't find your template file, loading default

Your app is running on http://localhost:3010

Building with Webpack...
Hash: e779570c713250e7b167
Version: webpack 1.12.9
Time: 424ms
  Asset     Size  Chunks       Chunk Names
main.js  21.5 kB       0       main
chunk    {0} main.js (main) 52 bytes [rendered]
    [0] multi main 52 bytes {0} [built] [3 errors]

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack-dev-server/client' in D:\Development\test-reapp\test-reapp
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'webpack/hot/only-dev-server' in D:\Development\test-reapp\test-reapp
 @ multi main

ERROR in multi main
Module not found: Error: Cannot resolve module 'babel-loader' in D:\Development\test-reapp\test-reapp
 @ multi main
webpack: bundle is now VALID.

Build took 0.424 seconds

```

Windows 10, npm:3.3.12, node: v5.1.1

**Comment by rahulinaction** [comment]
Any headsup

**Comment by funerr** [comment]
@rahulinaction what do you mean?

**Comment by rahulinaction** [comment]
Oops i wrote it broadly.Actually even I was facing the same problem.First i did add module in package.json and try npm install but that didnt solve the problem. I then tried this https://github.com/reapp/reapp/issues/102 mentioned and although it solved the error while reapp it shows undefined object error when i check it on browser console.

**Comment by ryd0rz** [comment]
This should now be resolved with latest version of reapp.

npm uninstall -g reapp
npm install -g reapp
reapp new test-reapp
cd test-reapp
reapp run
