### ISSUE TITLE
Blank screen with reapp build installing previous versions don't work

### ISSUE THREAD

**Issue by lduros** [reapp/reapp#116]
I have created an app that runs just fine when using "reapp run", reapp is installed globally from npm, but when running "reapp build web", I get a blank page for index.html. There's no JavaScript error either. 
I tried the following from the app directory:
npm install --save react@0.13.2
npm install --save reapp-ui@0.12.54
npm install --save reapp-kit@1.2.15

But this results in having a blank screen in both "reapp run" and "reapp build", and so it doesn't look like a solution. Has anyone been able to address this issue? I'll try to look into the differences between reapp-build and reapp-run and try to find out where the issue might be, but since I'm new to both react and reapp, I'd appreciate the help.

Thanks!

**Comment by lduros** [comment]
reapp run -e production also works, is there a way I could quickly convert the html/js available in reapp run -e production into an actual standalone js app?

**Comment by lduros** [comment]
Nevermind. This was an issue of mine with the router.

**Comment by Polycarpik** [comment]
Got the same problem after adding bootstrap. Routing seems fine. `reapp run` works fine. `reapp build` makes this 
```
Building... 

Building with webpack...
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Build complete
Copying ./assets/shared/ to ./build/web ...
Copying ./assets/web to ./build/web ...
```
and does nothing then. And doesn't finish either. When run index.html there is blank screen.
