### ISSUE TITLE
reapp new Error

### ISSUE THREAD

**Issue by evertonrobertoauler** [reapp/reapp#13]
Creating new reapp folder for: app...
Running git clone --depth=1 git@github.com:reapp/reapp-starter.git /home/myUser/app

 Error
{ [Error: Command failed: /bin/sh -c git clone --depth=1 git@github.com:reapp/reapp-starter.git /home/myUser/app

I change this file reapp-new:  

return promiseProcess('git clone --depth=1 git@github.com:reapp/reapp-starter.git ' + dest);

to

return promiseProcess('git clone --depth=1 https://github.com/reapp/reapp-starter ' + dest);

And now it's working, It'll be nice if you guys change it, to other users not to have the same problem

**Comment by pmtarantino** [comment]
Yes, it didn't work and then I changed it and it works. Thanks @evertonrobertoauler , it should be added to the repo.

**Comment by natew** [comment]
Fixed with reapp@0.5.24, thanks.
