### ISSUE TITLE
Integrate cordova

### ISSUE THREAD

**Issue by natew** [reapp/reapp#15]
I'd ideally like a few things:

1. Builds add in cordova js library and mimic cordova file structure so they are plug and play. Maybe with a flag.
2. Can specify a target dir for builds, so you can one step build into your cordova app
3. Look at ionic/supersonic cordova enhancements. Would be nice to have promisified libraries.

**Comment by titanjer** [comment]
Hi! Would you show the hints on how to migrate __reapp starter__ app to __cordova__? I copy __build/public/__ to __cordova__ __www/__ and do some file move, but __iOS__ emulator show me a blank page!

**Comment by olegpopadko** [comment]
Hi! I've the same behaviour as @titanjer.

**Comment by natew** [comment]
I'm actually prepping the hacker news app for the app store as we speak. It also took me quite a while to get it to work and there are a number of weird things you have to do.

I've been documenting all of that for a blog post, but also want to achieve "plug-and-play" builds where you can just link your build directory to your cordova app and it "just works". So need something like keeping a config.xml in your assets, etc.

All of that should be out in the coming week.

**Comment by olegpopadko** [comment]
Just hint ;)

**Comment by natew** [comment]
Check out the hacker news app in the reapp repos and the build.ios.js

**Comment by titanjer** [comment]
Ha! So silly I am!
I guess the problem was pushstate before and tried to fix that! but it does not work! @@
looking forward your blog! T^T

**Comment by natew** [comment]
Here's some more.

My config.xml:

```xml
<?xml version='1.0' encoding='utf-8'?>
<widget id="io.cordova.hellocordova" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>rHN</name>
    <description>
        Hacker News Reader, powered by Reapp (www.reapp.io).
    </description>
    <author email="nate@reapp.io" href="http://reapp.io">
        Reapp
    </author>
    <content src="index.html" />
    <access origin="*" />

    <preference name="DisallowOverscroll" value="true" />

    <preference name="SplashScreen" value="splash" />
    <preference name="SplashScreenDelay" value="1000" />

    <platform name="ios">
      <!-- iOS 8.0+ -->
      <!-- iPhone 6 Plus  -->
      <icon src="www/res/ios/Icon-60@3x.png" width="180" height="180" />
      <!-- iOS 7.0+ -->
      <!-- iPhone / iPod Touch  -->
      <icon src="www/res/ios/Icon-60.png" width="60" height="60" />
      <icon src="www/res/ios/Icon-60@2x.png" width="120" height="120" />
      <!-- iPad -->
      <icon src="www/res/ios/Icon-76.png" width="76" height="76" />
      <icon src="www/res/ios/Icon-76@2x.png" width="152" height="152" />
      <!-- iOS 6.1 -->
      <!-- Spotlight Icon -->
      <icon src="www/res/ios/Icon-Small-40.png" width="40" height="40" />
      <icon src="www/res/ios/Icon-Small-40@2x.png" width="80" height="80" />
      <!-- iPhone / iPod Touch -->
      <icon src="www/res/ios/Icon.png" width="57" height="57" />
      <icon src="www/res/ios/Icon@2x.png" width="114" height="114" />
      <!-- iPad -->
      <icon src="www/res/ios/Icon-72.png" width="72" height="72" />
      <icon src="www/res/ios/Icon-72@2x.png" width="144" height="144" />
      <!-- iPhone Spotlight and Settings Icon -->
      <icon src="www/res/ios/Icon-Small.png" width="29" height="29" />
      <icon src="www/res/ios/Icon-Small@2x.png" width="58" height="58" />
      <!-- iPad Spotlight and Settings Icon -->
      <icon src="www/res/ios/Icon-Small-50.png" width="50" height="50" />
      <icon src="www/res/ios/Icon-Small-50@2x.png" width="100" height="100" />

      <!-- splashes -->
      <splash src="www/res/screen/ios/Default.jpg" width="320" height="480"/>
      <splash src="www/res/screen/ios/Default@2x.jpg" width="640" height="960"/>
      <splash src="www/res/screen/ios/Default-568h@2x.jpg" width="640" height="1136"/>
      <splash src="www/res/screen/ios/Default-667h@2x.jpg" width="750" height="1334"/>
      <splash src="www/res/screen/ios/Default-Portrait-736h@3x.png" width="1242" height="2208"/>
    </platform>
</widget>
```

My index.html:

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
    <link href="css/main.css" rel="stylesheet" type="text/css">
    <script src="cordova.js"></script>

    <script>
      function loadApp() {
        console.log('loading app');
        var head = document.getElementsByTagName('head')[0];
        var script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = 'js/main.js';
        head.appendChild(script);
      }

      document.addEventListener("deviceready", loadApp, false);
    </script>
</head>

<body style="background:#dc781f;">
    <div id="app"></div>
</body>

</html>
```

Notice the delayed loading of the bundle! That's what fixed my problem.

**Comment by olegpopadko** [comment]
Thx a lot!
I'll try today.

**Comment by olegpopadko** [comment]
There isn't `build.ios.js` file in hacker news app repo. So a copied `config/build.js` to `config/build.ios.js` and replaced require of `./build.ios.config.js` with `./build.ios.config.js`. Then I use `npm run-script ios`. Or should I use `reapp build ios` instead?

**Comment by natew** [comment]
`reapp build ios` will look for the `build.ios.config.js` file and run that, so it should "just work" if you run that. Be sure you've updated `reapp` first and let me know if that works.

**Comment by olegpopadko** [comment]
I'm on 0.6.5 reapp version. `reapp build ios` search for `./build.iosconfig.js` instead of `./build.ios.config.js`. Attempts are still unsuccessful.

**Comment by olegpopadko** [comment]
And with this configuration I have `Error: No template for dependency: TemplateArgumentDependency` on `reapp build ios`

**Comment by natew** [comment]
Should be fixed with the new version of reapp. The template dependency I haven't seen, later today I'll run through a fresh install.

**Comment by olegpopadko** [comment]
Do you use any plugin for cordova? React router doesn't handle location properly within WebView. The application act as if started without a server.

**Comment by natew** [comment]
Ah yea you need to build for iOS. Check the config folder of the hacker news app. I believe you could use reapp build ios and that would work. I'm on my mobile now but I can explain better in a bit.

Also be sure you're up to date with reapp-routes.

**Comment by natew** [comment]
@olegpopadko could you paste in the output of `reapp build ios -d`?

**Comment by olegpopadko** [comment]
I'd update reapp and reapp-routes to last versions from github and everything works like a charm. Awesome! Thanks!

**Comment by olegpopadko** [comment]
I don't use `./build.ios.config.js` because I still have `Error: No template for dependency: TemplateArgumentDependency` with it.

**Comment by titanjer** [comment]
Hi! I followed the __example-cordova-app__ steps on android device but needs these fixes below! 

1. Modify __"/main.css"__ in index.html to __"main.css"__
2. Library __axn__ needs ES6 Promise support, please install cordova PromisePlugin.

**Comment by natew** [comment]
@titanjer for promises you can require a promise library and export it as well. The reapp-routes/react-router (default) uses Bluebird already, which we are looking into a better way, but perhaps we could just do it for you.

Either way:

```
var { Promise } = require('bluebird');
window.Promise = Promise;
```

See if that works.

**Comment by natew** [comment]
This has been pretty much completed. There are initial docs, but we'll add more as we go.
