### ISSUE TITLE
Routing error for 'Sub' component when loading new app from CLI template

### ISSUE THREAD

**Issue by zenlambda** [reapp/reapp#26]
Reproducer

```
reapp new myreapp
cd myreapp
# apply workaround for issue #25 (move layout file)
reapp run
```

Loading localhost:3010 and opening the console shows:

```
 Uncaught Error: Cannot find module './components/Sub'.
```

This must be because the Sub component may have change recently from ./components/Sub.jsx to ./components/home/Sub.jsx and the route 'generator' needs updating.

**Comment by zenlambda** [comment]
The reapp/reapp-starter#2 PR I just did specifies the home directory along with the home 'route' rather than trying to change the generator function. Not sure this is how its supposed to work since I thought I read somewhere that the generator is supposed to infer the project structure from the route specification, however I have not been able to locate the generator function so this is the easiest fix for me.

**Comment by natew** [comment]
After fixing your last PR I went and checked that this worked, and it seems to be fine for me. Perhaps something weird happened? Can you try updating the CLI to the latest and running again? Hopefully that works. Apologies for the hassle, we are moving fast at this point but 0.10 should bring some fun stuff.

**Comment by zenlambda** [comment]
I've uninstalled my previous reapp cli and upgraded to 0.6.12 that you just pushed out. I'm still getting this issue I'm afraid.

**Comment by zenlambda** [comment]
I think this maybe caused by the way that babel handles rest arguments in the [route generation code](https://github.com/reapp/reapp-routes/blob/master/index.js#L23) (see babel/babel#918).

Basically the home entry gets corrupted because babel uses the arguments variable for 'rest' subscripts which does not accurately mirror the state of rest after .shift() is called on rest.

**Comment by natew** [comment]
Ah, thanks so much. Was wondering because it worked well for me. Looks like theres a fix out. Going to update the packages accordingly.

Let me know if you run into anything else. Everything's a little messy as I'm landing some big changes for 0.10 but hopefully not too bad.

**Comment by natew** [comment]
Should be out in 0.6.13 (with reapp-pack 1.2.4)

**Comment by zenlambda** [comment]
Thanks I just tested the new release and it works fine!
