### ISSUE TITLE
reapp new appname githubtemplate

### ISSUE THREAD

**Issue by natew** [reapp/reapp#29]
Because there are a few different style of base apps we'd want to present & this should be pretty easy to add. Let's allow the `new` command to take an option to clone different repos.

- `reapp new app` defaults to our reapp-starter repo
- `reapp new app flux` grabs our flux repo
- `reapp new app empty` grabs empty repo, no scaffolding included

This needs some thought re: upgrading. Don't want to overcomplicate things too much with that. And third party repos would be cool too:

- `reapp new app user/repo-name`

**Comment by natew** [comment]
This actually is released in 0.7, but not documented.

**Comment by arsemyonov** [comment]
What about using `ssh` instead of `https`?

```
➜  reapp new app flux

Creating new reapp folder for: app...
Running git clone --depth=1 https://github.com/reapp/starter-flux  <destination>...
Username for 'https://github.com':
Password for 'https://github.com':
```

**Comment by natew** [comment]
How to use ssh with github?

**Comment by natew** [comment]
Sorry was on the run when I wrote that. Would that avoid requiring an ssh key though? It seems both would use ssh right?

**Comment by arsemyonov** [comment]
@natew heh, I didn't see that `starter-flux` is missing (or hidden), so that's why github asked me login/password.

Everything is OK, no worries then :)

**Comment by natew** [comment]
@arsemyonov where did you see docs for the flux syntax? I should remove those for now :)
