### ISSUE TITLE
Upon first `reapp run`. Error message to run npm install in reapp-pack. Non-critical?

### ISSUE THREAD

**Issue by megalithic** [reapp/reapp#3]
Just updated reapp package to latest, -V for me shows 0.5.19, however i see package.json shows 0.5.18. At any rate, I created a new reapp, cd into that new reapp and run `reapp run` for first time.

The App runs, but console output results in:
```sh
Error! Make sure you have run npm install in reapp-pack
Error! Make sure you have run npm install in reapp-pack
Starting...
Running express server on 3010 ...
Starting Webpack server on localhost 3011 ...
webpack: wait until bundle finished: /main.js
Hash: 60c045f881f7c8ec9aa7
Version: webpack 1.5.3
Time: 14041ms
```

So, it **DOES** run, but just wanted to confirm those duplicated logged errors are indeed non-critical.

Nothing to worry about at the moment?

**Comment by natew** [comment]
Yea I've seen the errors on other machines before, I need to look into them, but they aren't critical. Thanks for the report though, I'll check into it.

**Comment by megalithic** [comment]
thanks @natew. feel free to close this issue then.

**Comment by natew** [comment]
Going to close because we've updated a lot, will see if anyone else reports it.

**Comment by douyw** [comment]
This message still appears when `reapp build`. The console output:

```
$ reapp -V
0.6.13
$ reapp build
Error! Make sure you have run npm install in reapp-pack
Error! Make sure you have run npm install in reapp-pack
Building...

Note: The code generator has deoptimised the styling of "/Users/mac/pdev/reapp/myreapp/node_modules/reapp-routes/node_modules/bluebird/js/browser/bluebird.js" as it exceeds the max of "100KB".
Build complete
```
