### ISSUE TITLE
Lists do not show styles

### ISSUE THREAD

**Issue by joshnur** [reapp/reapp#30]
The issue is visible on ordered lists:
`<ol>
     <li>A test</li>
     <li>B test</li>
 </ol>`

The number will not appear. Similarly, the `<ul>` tag has no visible styling like bullet points to it.

(Tested on Home.jsx and Web only)

**Comment by natew** [comment]
Hey, put in a fix for this. I took off the flex styling on ul and li elements that was there before and check that the ul looked ok. This should be fixed up! Let me know if you see an issue with the latest reapp-ui and I can investigate.
