### ISSUE TITLE
Reapp for the web

### ISSUE THREAD

**Issue by hartmamt** [reapp/reapp#31]
Any issues with writing an app using reapp that isn't immediately targeted for running inside an app?  Can Reapp be used as a framework for single page apps?

**Comment by natew** [comment]
Absolutely. In fact our early plans were to market it just as a great SPA app platform, but we're focusing on mobile first and then will expand in the future. But it's a great way to get rolling with React in general.

**Comment by fifafu** [comment]
This is great, Reapp looks very cool and I'm also looking to use it as general SPA app platform. I'm just learning React now but hope I'll be able to contribute soon.
