### ISSUE TITLE
Chrome does not render new app

### ISSUE THREAD

**Issue by bugthing** [reapp/reapp#33]
After running `reapp new myapp` and then `reapp-run`, when I visit `http://localhost:3010/` in Firefox, I see the basic app, but visiting in Chrome I see nothing.

Developer tools is showing the following error:

Uncaught TypeError: Object.getPrototypeOf called on non-object

**Comment by natew** [comment]
Could you paste where it reports the line of the error?

**Comment by bugthing** [comment]
I have updated reapp and it works now .. highly likely it was some fail of mine :panda_face:
