### ISSUE TITLE
build faild

### ISSUE THREAD

**Issue by sunweifeng** [reapp/reapp#39]
after builded the project, open the index.html in./build/web/, but the page has nothing?

logs here:

newsapp git:(master) reapp build -d
Looking for config file: /Users/sunweifeng/reapp/newsapp/config/build.config.js
Making webpack config with:
 { linkModules: true,
  entry: './app/app.js',
  devtool: 'none',
  target: 'web',
  debug: true,
  env: 'production',
  minify: true,
  separateStylesheet: true,
  name: 'build',
  platform: 'web',
  dir: '/Users/sunweifeng/reapp/newsapp',
  hostname: 'localhost' }

Not running babel on modules... node_modules\/bluebird\/, node_modules\/fynx\/, node_modules\/immutable\/, node_modules\/lodash\.isequal\/, node_modules\/lodash\.pick\/, node_modules\/omniscient\/, node_modules\/parseurl\/, node_modules\/qs\/, node_modules\/react\/, node_modules\/reapp\-request\/, node_modules\/superagent\/, node_modules\/superagent\-bluebird\-promise\/, socket\.io

Webpack config:
{ hostname: 'localhost',
  entry: { main: './app/app.js' },
  output:
   { path: '/Users/sunweifeng/reapp/newsapp/build/web',
     filename: '[name].js',
     chunkFilename: '[id].js',
     publicPath: '/',
     sourceMapFilename: 'debugging/[file].map',
     libraryTarget: undefined,
     pathinfo: true },
  target: 'web',
  module:
   { loaders:
      [ { test: /\.json$/, loader: 'json-loader' },
        { test: /\.(png|jpg|jpeg|gif)$/,
          loader: 'url-loader?limit=10000&name=[name].[ext]' },
        { test: /\.svg$/, loader: 'raw-loader' },
        { test: /\.html$/, loader: 'file-loader?name=[name].[ext]' },
        { test: /\.worker\.js$/, loader: 'worker-loader?inline=true' },
        { test: /\.jsx?$/,
          loader: 'babel-loader?experimental=true&optional=bluebirdCoroutines',
          exclude: /node_modules\/bluebird\/|node_modules\/fynx\/|node_modules\/immutable\/|node_modules\/lodash\.isequal\/|node_modules\/lodash\.pick\/|node_modules\/omniscient\/|node_modules\/parseurl\/|node_modules\/qs\/|node_modules\/react\/|node_modules\/reapp\-request\/|node_modules\/superagent\/|node_modules\/superagent\-bluebird\-promise\/|socket\.io/ },
        { test: /\.css$/,
          loader: '/usr/local/lib/node_modules/reapp/node_modules/reapp-pack/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader!autoprefixer-loader?browsers=last 2 version' },
        { test: /\.styl$/,
          loader: '/usr/local/lib/node_modules/reapp/node_modules/reapp-pack/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader!autoprefixer-loader?browsers=last 2 version!stylus-loader' } ] },
  devtool: 'none',
  debug: true,
  resolveLoader:
   { root: '/Users/sunweifeng/reapp/newsapp/server_modules',
     alias: {} },
  externals: [],
  resolve:
   { root: [ '/Users/sunweifeng/reapp/newsapp' ],
     modulesDirectories: [ 'node_modules', 'web_modules', 'server_modules', 'app' ],
     extensions: [ '', '.web.js', '.js', '.jsx' ],
     alias: {},
     fallback:
      [ '/Users/sunweifeng/reapp/newsapp/node_modules',
        '/Users/sunweifeng/reapp/newsapp/server_modules' ] },
  plugins:
   [ { definitions: { 'process.env': { NODE_ENV: '"production"', TARGET: '"web"', PLATFORM: '"web"' } } },
     { request: 'react' },
     { request: 'react/lib/ReactComponentBrowserEnvironment' },
     [Function],
     { filename: '[name].css', options: {}, id: 1 },
     { options: { compress: { warnings: false } } },
     {} ] }

Copying layout /Users/sunweifeng/reapp/newsapp/assets/web/index.html
Making layout with scripts:  [ 'main' ]
Recreate build dir: /Users/sunweifeng/reapp/newsapp/build/web
Building...

Building with webpack...
Had warnings:
./app/routes.js
Critical dependencies:
6:16-23 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/routes.js 6:16-23

./app ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./app ^\.\/.*$

./app ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./app ^\.\/.*$

undefined '\n\n'
Build complete
Copying ./assets/shared/ to ./build/web ...
Copying ./assets/web to ./build/web ...
Writing layout:  ./build/web/index.html

**Comment by natew** [comment]
What's in your /assets/web/index.html file?

**Comment by sunweifeng** [comment]
get resource from here(https://github.com/reapp/hacker-news-app), and change nothing, reapp run was ok, but build failed.

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta charset="utf-8">

  <link rel="apple-touch-icon" href="/assets/icon.png"/>
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/icon.png"/>
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/icon.png"/>
  <title>Hacker News</title>
  
</head>
<body>
  <div id="app"></div>
  
  
</body>
</html>

**Comment by sunweifeng** [comment]
http://sunweifeng.com/demo/web/index.html
demo here~, using resource from the folder of build.
is that anything required to run the page after build? centos+apache+php

**Comment by natew** [comment]
Yes, you need to run it from the base pathname, so in your case from http://sunweifeng.com, because the router you use is expecting that to be your root URL. The code looks good though, you'd just need to run it from "/"

**Comment by sunweifeng** [comment]
thx, i'll try it later :+1:

**Comment by sunweifeng** [comment]
Hi natew,
I want to run it as webapp, like http://kitchen.reapp.io/#demo:emulateTouch as, so how to place the files from build/web folder into my server？

**Comment by natew** [comment]
You'd need to figure out how to host it! You can use any host and just upload the files to be served. This is outside of scope of Reapp though, check out a simple hosting provider and their docs.

**Comment by sunweifeng** [comment]
.... exactly I know how to upload the files to the host, I mean that whether reapp istalled is required in my host, because now the page(http://sunweifeng.com/demo/web/index.html) is empty now.

as you said 'run it from the base pathname', but the base pathname(http://sunweifeng.com) in my host do not has any connection to http://sunweifeng.com/demo/web/index.html
