### ISSUE TITLE
bind to address (-b) broken

### ISSUE THREAD

**Issue by mbrookes** [reapp/reapp#41]
Works when accessed by IP on the local machine, but not from the network.

**Comment by natew** [comment]
Not familiar with this but here's the PR that added this feature, is it working for you still @jrhicks ?

https://github.com/reapp/reapp/pull/32

**Comment by jrhicks** [comment]
@mbrookes @natew Works for me where my server is a vagrant box and the client is my host machine.  I use the comamnd

    reapp run -b 0.0.0.0

@mbrookes When you run it from a seperate machine do you specify the host name also

    reapp run -b 0.0.0.0 -h [hostNameOfServerHere]

Thanks :)

**Comment by mbrookes** [comment]
@jrhicks If I speficy the hostname `reapp run -h [hostNameOfServerHere]`, then I don't need to specify the bind adress, and can access from a client on the same subnet.

What doesn't seem to work is `reapp run -b 0.0.0.0` on the 'server' (my laptop) and accessing it from a client (Safari on iPhone).  It seems to load the HTML, as the loading bar dissapears and the site-name is in the history, but I get a busy spinner in the network bar at the top of the screen, and the page content never appears.

**Comment by jrhicks** [comment]
@mbrookes Before the pull request the host was used for both the bind address and as the base url in the HTML to fetch the assets.  For my situation, I needed bind and host to be different.  I needed the base url to remain localhost, but the bind address to be 0.0.0.0

Check the generated HTML ... whatever you specifiy as host ... will be in the base url to your assets.  If I remember correclty.

**Comment by mbrookes** [comment]
@jrhicks You're right - the URL for main.js has the hostname hard-coded when it should be relative. Not familiar enough (or at all :smile: ) with the underlying tools to know what part of the build precess is breaking that.

**Comment by natew** [comment]
@mbrookes is this working alright then?

**Comment by jrhicks** [comment]
@natew it works ... possibly not intuitive that you must specify a host since it is hard coded into the index.html file.

**Comment by natew** [comment]
It shouldn't be hardcoded, it gets written in based on what you pass it. I think I may be writing in the wrong one then. Possible just some logic in the build step that's using host over bind.

**Comment by mbrookes** [comment]
It shouldn't be adding the hostname at all I don't think. From a users perspective, it should be possible to specify an IP of 0.0.0.0, then browse to any IP or hostname assigned to the machine, for example machinename.local or localhost. The hostname added to index.html currently prevents this.

**Comment by natew** [comment]
It adds the hostname because you server the webpack file on a different port from the file you hit. So if I run on port 3010, the javascript file is server on 3011 (because thats where webpack-dev-server is running).

**Comment by mbrookes** [comment]
Sorry, yes meant to revisit this issue having realised that. 

In that case binding to 0.0.0.0 in the normal way won't be possible, unless the hostname added to index.html is generated dynamically based on the IP address that the client is connecting to (with the port changed to that for the webpack server).

**Comment by casio** [comment]
+1 on having `bind` (and `host` for that matter) work in the normal/expected manner: http://en.wikipedia.org/wiki/0.0.0.0

I'm new to reapp and it was one of the first moments with the framework that I stumbled upon this issue(while trying to check kichtensink on a real mobile device)

If however it makes sense to serve eg. the actual assets from a different host than the html, then that should be a separate cli option(defaulting to the host value derived from `host/bind`), imho
