### ISSUE TITLE
is normal than input elements doesnt works in the browser?

### ISSUE THREAD

**Issue by cocodrino** [reapp/reapp#42]
Hi, I'm curious because seems not works in chrome nor firefox and I cant find any issue open here, I've not tried in my phone yet  but how do you test input elements in development?..thanks

**Comment by natew** [comment]
Seems like we introduced a bud recently they work when you emulate mobile devices in chrome. I have an idea why it's happening, thanks for opening the ticket.

**Comment by natew** [comment]
This should be fixed in reapp-ui@87185e79
