### ISSUE TITLE
reapp run: Uncaught TypeError: Cannot read property 'self' of undefined

### ISSUE THREAD

**Issue by rkmax** [reapp/reapp#44]
I recently start with reapp. I'm using Linux so first install `sudo npm install -g reapp` later do

    $ reapp create my-app
    $ cd my-app
    $ reapp run

open my application on http:localhost:3010 but I try to change for example the title on Home.jsx and i get the following error

![captura de pantalla de 2015-04-12 22-19-33](https://cloud.githubusercontent.com/assets/395707/7109362/06316b7e-e162-11e4-9010-e877c66000c3.png)

**Comment by roshanca** [comment]
Same error to me in my Yosemite.

**Comment by natew** [comment]
Tested out install today and fixed up a few things. Let me know if this is still broken.

**Comment by rkmax** [comment]
@natew same error using 0.8.23

**Comment by natew** [comment]
Did you update your reapp-kit/reapp-ui versions?

**Comment by rkmax** [comment]
Yes I ran `sudo npm install -g reapp` and later in the project `npm update`
```
reapp-kit@1.2.9 node_modules/reapp-kit
├── reapp-object-assign@1.0.0
├── immutable@3.7.2
├── bluebird@2.9.24
├── fynx@1.6.0 (axn@1.6.1)
├── reapp-routes@0.10.10 (reapp-platform@1.0.7)
├── react-router@0.13.2 (object-assign@2.0.0, classnames@1.1.4, qs@2.4.1)
├── omniscient@3.1.0 (lodash.pick@3.1.0, lodash.isequal@3.0.1, lodash.assign@3.0.0)
├── isomorphic-fetch@2.0.1 (whatwg-fetch@0.7.0, node-fetch@1.0.6)
└── reapp-ui@0.12.39 (reapp-raf-batching@1.0.0, reapp-component@1.0.2, classnames@1.2.0, observable-state@0.3.4, reapp-scroller@1.0.8, react-document-title@1.0.2, lodash.merge@3.1.0, css-to-matrix@1.0.0, react-animate-state@1.0.1, react-style@0.5.3)
```

**Comment by natew** [comment]
This may have to do with: facebook/react#3404 (fixed in facebook/react#3494). This should get into 0.13.2: facebook/react#3629.

For the record, I just tried making a new app and running it and it doesn't give me these problems, hot reloading seems to work just fine. Try updating your React to master perhaps as a temporary fix, I will see if I can patch the error as well internally so it doesn't break.

**Comment by rkmax** [comment]
@natew I just create a new app and have the same error :(. I try to install the master version of react using this dependencies
![captura de pantalla de 2015-04-15 09-01-09](https://cloud.githubusercontent.com/assets/395707/7160338/fd1a4c2a-e34d-11e4-9e30-897ace3ccd4b.png)

but not works!

**Comment by natew** [comment]
Don't have much time today but tried something, let me know if that works. If not can you show me the Styled file where it errors?

**Comment by rkmax** [comment]
![captura de pantalla de 2015-04-15 22-31-50](https://cloud.githubusercontent.com/assets/395707/7173562/40b18d88-e3bf-11e4-80ac-8905fc269de1.png)


Here https://github.com/reapp/reapp-ui/blob/master/src/mixins/Styled.js#L49

**Comment by natew** [comment]
This should be fixed if you update to latest reapp and react 0.13.2. Let me know if that's fixed.

**Comment by rkmax** [comment]
I'll try tomorrow, thanks for the info

**Comment by natew** [comment]
Closing unless still an issue with new React.
