### ISSUE TITLE
node.js requirement

### ISSUE THREAD

**Issue by kirrg001** [reapp/reapp#45]
hey,

can you add dependency to your docu?

nvm install 0.11.13
i couldnt run reapp because native promise wasnt provided by version ~10.x.x.

kirrg

**Comment by natew** [comment]
Good point. It should shim promises though by default by using Bluebird, but I can add a note. Where did you see the error?

**Comment by kirrg001** [comment]
when running

reapp new [name]

````
/usr/local/lib/node_modules/reapp/bin/reapp-new:69
  return new Promise(function(resolve, reject) {
             ^
ReferenceError: Promise is not defined
    at makeFolder (/usr/local/lib/node_modules/reapp/bin/reapp-new:69:14)
````

**Comment by patrickomeara** [comment]
+1

**Comment by natew** [comment]
Ah interesting. My mistake. I had Bluebird installed originally and took it out because it worked on my machine, but forgot it was new to 0.12. I should remove that requirement.

**Comment by natew** [comment]
Ok added lightweight promise polyfill for 0.10 users. Thanks for the report everyone.
