### ISSUE TITLE
Hot reloader not working

### ISSUE THREAD

**Issue by jbhatab** [reapp/reapp#48]
Just wanted to point out that when I install reapp, make a default app, and run it that the hot loader doesn't work out of the box for me.

**Comment by natew** [comment]
Seems to be working for me, just did a reapp new and edited Hello World! and I can see it changing as I save.

Can you describe whats happening?

**Comment by jbhatab** [comment]
Good enough for me. May just be something specific to me then. 

It's just not reloading the page when I save the changes, but it's not really bothering me much. You can close this if you want.

**Comment by natew** [comment]
Ok, it should work in most cases, sometimes if you edit external theme files it won't update, but other than that it should work. Feel free to upload anything from `reapp run -d` or from your `npm outdated`.
