### ISSUE TITLE
Deeply nested routes

### ISSUE THREAD

**Issue by jbhatab** [reapp/reapp#51]
I'm trying to setup a simple app that has a home page that goes to multiple master detail type views. I got the home page setup right so I can go to the master pages that have lists of the models. I'm having trouble getting the master pages going to the detail pages though. Here's some screenshots of what I have so far. I have the detail page coded but I can't access it.

![evue reapp 1](https://cloud.githubusercontent.com/assets/2458718/7282936/c302ccf0-e8f8-11e4-8595-9e3994cfd962.png)
![evue reapp 2](https://cloud.githubusercontent.com/assets/2458718/7282937/c30337ee-e8f8-11e4-913c-b9119f9c9aea.png)

Here's relevant code,

app/components/Home.jsx (works fine)
```
import { Reapp, React, NestedViewList, View, Button, List, ListItem } from 'reapp-kit'


class Home extends React.Component {  
  render() {
    return (
      <NestedViewList {...this.props.viewListProps}>
        <View title="evue-reapp">
          <List>
            <ListItem onTap={() => this.router().transitionTo('production-points')} icon>
              Production Points
            </ListItem>
            <ListItem onTap={() => this.router().transitionTo('users')} icon>
              Users
            </ListItem>
            <ListItem onTap={() => this.router().transitionTo('customers')} icon>
              Customers
            </ListItem>
            <ListItem onTap={() => this.router().transitionTo('sort-classes')} icon>
              Sort Classes
            </ListItem>
          </List>
          
        </View>

        {this.props.child()}
      </NestedViewList>
    );
  }
}

export default Reapp(Home);
```

app/components/ProductionPoints.jsx (works fine except it can't go to the detail page)
```
import { React, View, NestedViewList, BackButton, List, ListItem } from 'reapp-kit';
import $ from 'jquery'
import _ from 'underscore'
import { RoutedViewListMixin } from 'reapp-kit'

export default class extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      perspectives: []
    }
  }

  componentDidMount() {
    console.log()
    $.ajax({
      type: 'GET',
      url: "http://localhost:3000/api/perspectives/setup_index.json",
      format: 'json',
      success:(response) => {
        this.setState({perspectives: response.perspectives})
      },
      error:(response) => {
        console.log('error')
      }
    })
  }

  render() {
    const backButton =
      <BackButton onTap={() => window.history.back()} />

    return (
      <View {...this.props} title='Production Points' titleLeft={backButton}>
        { this.renderList() }
      </View>
    );
  }

  renderList() {
    if(this.state.perspectives.length > 0) {
      return (
        <List>
          {_.map(this.state.perspectives, (perspective) => {
            return (
              <ListItem key={ perspective.id } onTap={() => this.router().transitionTo('production-points-show', {id: perspective.id})} icon>
                { perspective.name }
              </ListItem>
            )
          })}
        </List>
      )
    }
  }
}
```

app/app.js
```
import './theme';
import { router, route } from 'reapp-kit';

router(require,
  route('home', '/',
    route('production-points',
      route('production-points-show', '/production-points/:id')
    ),
    route('users',
      route('users-show', 'users/:id')
    ),
    route('customers',
      route('customers-show', 'customers/:id')
    ),
    route('sort-classes',
      route('sort-classes-show', 'sort-classes/:id')
    )
  )
);
```

I think I set the routes up correctly but I just can't figure out how to do the deeply nested routes. I was looking at the kitchen sink code and it had some really weird things going on there with outer views, inner views, dotted view lists, and nestedview lists. But that code seemed to be outdated compared to the live one you had so I don't know how good it is to exactly copy that repo.

If there is just higher level advice to set this up, I would love some help.

Thanks!!

**Comment by natew** [comment]
Yea, documentation here could be a lot better. Your subsequent parent routes require you to extend React.Page rather than React.Component.

This gives you the RouteHandler methods you need for children:

```js
export default class extends React.Page {
  //...

  render() {
    const Child = this.childRouteHandler();

    const backButton =
      <BackButton onTap={() => window.history.back()} />

    return (
      <View {...this.props} title='Production Points' titleLeft={backButton}>
        { this.renderList() }

         {Child}
      </View>
    );
  }
}
```


That should render Child. You may need to use <Child />, I can't remember and am super busy atm, but give it a shot. The docs for this need to be released, just in the midst of a lot of stuff.

**Comment by jbhatab** [comment]
It kinda worked. I did get the other view up, but a few other things came up that opened up a few more questions but I'm just gonna play with it. Thanks.

**Comment by clauderic** [comment]
I've been struggling with this also and the only way I've sort of managed to get it to work is with a nested <NestedViewList> within a <View>, but that has a set of drawbacks in terms of animations and layout. 

Any chance you could provide a basic implementation example of how to get deeply nested routes to work with the Router with the following example:
```javascript
router(require,
  route('home', '/',
    route('sub',
    	route('sub2')
    )
  )
);
```

**Comment by natew** [comment]
There's another thread somewhere with @mbrookes where we discussed this at length, need to find it.

**Comment by natew** [comment]
Maybe not, basically sub routes are different than the top level and you want to do `class extends React.Page` and and then inside do `this.createChildRoute()`, I believe. Apologies I am a little tied at the moment.

**Comment by clauderic** [comment]
This is what I currently have (not working):
Sub.jsx:
```javascript
class Sub extends React.Page {
	constructor(props) {
		super(props);
	}
	render() {
		return (
			<View {...this.props}>
			 	<NestedViewList>
			 		<View title="First sub route">
			 			<Button onClick={() => this.router().transitionTo('sub2')}>Go to nested sub route</Button>
			    	</View>
			    	{this.childRouteHandler()}
				</NestedViewList>
			</View>
		);
	}
}
```
sub/Sub2.jsx:
```javascript
class Sub2 extends React.Component {
	constructor(props) {
		super(props);
	}
	render() {
		const backButton = <BackButton chromeless onTap={() => this.router().transitionTo('sub')} />;

		return (
	 		<View title={[backButton, "Nested sub route"]} {...this.props}>
		 		<p>Nested sub route content</p>
	    	</View>
		);
	}
}
```

**Comment by clauderic** [comment]
If I set up a helper goTo() function that not only calls this.router().transitionTo but also increments the <NestedViewList scrollToStep={this.state.step} /> value, it works. 

However, the element gets immediately removed from the DOM when moving backwards, which doesn't make for a smooth transition. Any way to fix this?
