### ISSUE TITLE
UI glitch Title bar

### ISSUE THREAD

**Issue by morenoh149** [reapp/reapp#53]
Hello. Great project!

I've encountered the following when developing a simple app. Any fixes appreciated.
![screenshot 2015-04-23 17 10 45](https://cloud.githubusercontent.com/assets/587438/7310121/bdb25642-e9db-11e4-8eab-5a40c861087e.png)
Closest I could narrow it down is to a `class='View--inner` div;
![screenshot 2015-04-23 17 13 59](https://cloud.githubusercontent.com/assets/587438/7310157/3bbdc594-e9dc-11e4-89bd-993ef8d18515.png)

**Comment by natew** [comment]
Interesting... wish there was a better way for people to just send the full html/js output of a page for debugging. What's the context it's doing that in? Any chance you could provide a gist of what reproduces it?

**Comment by morenoh149** [comment]
nope. the code is available here https://github.com/r3dm/alarmClock/blob/master/app/components/Home.jsx

**Comment by geordee** [comment]
It looks like you TitleBar is transparent somehow. I do not get this. Try upgrading the libraries.

**Comment by morenoh149** [comment]
@geordee that didn't do it. But thanks for checking it out.

**Comment by morenoh149** [comment]
I'm closing this as I see it in a vanilla reapp project. But it goes away if I use Firefox or a private chrome session. It's probably due to one of my chrome extensions.
