### ISSUE TITLE
Nesting components throwing "Uncaught TypeError: Cannot read property 'toUpperCase' of undefined"

### ISSUE THREAD

**Issue by jay3dec** [reapp/reapp#55]
I was trying to nest a component called `MyView` into another one. But it throws the error 
```
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined ReactDefaultInjection.js:53
```

Here is my code 
```
import { Reapp, React, View } from 'reapp-kit';

class Home extends React.Component {
  render() {
    return (
      
        <View title="TestRe">
          <p>Hello, World!</p>

          <MyView />
        </View>

     
    );
  }
}

var MyView = React.createClass({

   render: function() {
      return (
       
          <div><span>Hello</span></div>
      );
    }
});

export default Reapp(Home);

```

Now if I set the default component as MyView it works fine.
Any thoughts what might be wrong ??

**Comment by natew** [comment]
Usually this error means you have two versions of React in your bundle. I'd check down your node_modules and be sure you don't have a duplicate React.

**Comment by jay3dec** [comment]
@natew I was able to resolve the above issue by moving `MyView` before `Home`. Anyways thanks :)

**Comment by ryd0rz** [comment]
For those who hit this error message, another thing to look at is that you are exporting your nested component properly.

es6 syntax example:
export class NestedComponent extends React.Component {
  .... component code ...
  render() {
    return (
      <div>
        ... render component ...
      </div>
    );
}

**Comment by salehhamadeh** [comment]
@ryd0rz I've been trying to fix a bug like this for hours. The bug occurs when I render ReactTransitionGroup. I am using the code in this gist: https://gist.github.com/tkafka/0d94c6ec94297bb67091
Do you know what's the issue by just looking at this gist?

**Comment by salehhamadeh** [comment]
I found what the issue was. My problem was that I was doing
var ReactTransitionGroup = React.addons.ReactTransitionGroup;
I fixed it by changing it to
var ReactTransitionGroup = React.addons.TransitionGroup;

**Comment by Subha** [comment]
@jay3dec Thanks I had a similar issue in my react App and moved my React.render function at the end. I was sitting on this issue for about an hour. I feel there is no good debugger for react (chrome extension) did not help me here.

**Comment by jay3dec** [comment]
@Subha great :)

**Comment by bblumberg** [comment]
I am having a similar problem. I have a tree of components (so the children are of the same type as the parent) and when I do:

function renderChildren(){
  // clone children
  return (React.Children.map(this.props.children, function(child) {
    return React.cloneElement(child, {foo: false})
  }.bind(this)));
};

I get the dreaded: Warning: Only functions or strings can be mounted as React components.
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
  autoGenerateWrapperClass	...

Any help would be greatly appreciated. Thanks.

**Comment by rapilabs** [comment]
@salehhamadeh mate, i just did exactly the same thing and didn't realise until i read your comment :)

**Comment by bblumberg** [comment]
It seems like the children need to be of another class for it to work. In my case I created a new class ( e.g., NodeGroup) and inside its render method, I cloned the children which are of a different type  (Node) and it all worked.

**Comment by salehhamadeh** [comment]
@rapilabs I'm glad you were able to catch it. These bugs are the productivity killers of software engineers.

**Comment by trusktr** [comment]
I just had this problem too. In case someone stumbles on this, the cause in my case was that I had comments in my JSX like so:

```jsx
return (
  <div>
    // This isn't a comment!
    <span>foo</span>
  </div>
)
```

And so React would treat the comment as a child (an invalid child at that) and throw that horrible error.
