### ISSUE TITLE
Problems passing props

### ISSUE THREAD

**Issue by jefffriesen** [reapp/reapp#56]
It seems like there may be something going on when you wrap React components with Reapp. How do you get props passed?

#### Home.jsx
```
import { Reapp, React, NestedViewList, View, Button, Grid } from 'reapp-kit';
import Test from './home/test.jsx'

class Home extends React.Component {

  render() {
    return (
      <div>
        <Test testCopy='howdy' />
      </div>
    );
  }
}

export default Reapp(Home);
```

#### Test.jsx
```
import { Reapp, React, Grid, Button } from 'reapp-kit';

class Test extends React.Component {

  render() {
    return (
      <div>
        <h3>Here's the test copy</h3>
        {this.props.testCopy}    {/* nothing outputs */}
      </div>
    );
  }
}

export default Reapp(Test);
```

I can't get props to be passed to a child component. I'm thinking this is one of three possibilities:
1. I'm making a simple mistake
2. There is new stuff in ES6 and React 0.13 that I don't understand. I've looked at the docs and this article and didn't see any mention of how props are passed: http://www.newmediacampaigns.com/blog/refactoring-react-components-to-es6-classes
3. There is some magic going on with the wrapper components. For example, I don't know what this is doing in the `<Home />` component in the vanilla install:
```
{this.props.child()}
```

Or why `...this.props` is in the View component
```
<View {...this.props} title="Sub Route" titleLeft={backButton}>
```
Are these wrapper components and spread operators required on every component? I would like to be able to use Reapp sometimes without the special layout components.

Any insight would be really appreciated. Thank you

**Comment by timuric** [comment]
@jefffriesen In test.jsx you don't have to  add reapp wrapper `Reapp(Test)` . And  `{...this.props}` is used to pass all props of `this` to `<View>`. 

A good way to understand the way information flows through components is to inspect tree using React dev tools https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en

If are you missing something in documentation try to read source of Reapp components, most of the time it is quite easy to follow.

**Comment by jefffriesen** [comment]
Ok, thanks for the explanation.
