### ISSUE TITLE
Reapp new breaks on windows with dest paths containing spaces

### ISSUE THREAD

**Issue by WrathZA** [reapp/reapp#59]
Creating new reapp folder for: flickrapp...
Running git clone --depth=1 https://github.com/reapp/starter-default C:\Users\B\Google Drive\Projects\reapp/flickrap
p...
 Error
{ [Error: Command failed: Too many arguments.

*Fixed by escaping dest in cloneRepo()*

function cloneRepo() {
  if (Program.debug)
    console.log('Looking for template in %s', getRepo());

  return promiseProcess(
   //Works now by escaping dest. 
    'git clone --depth=1 '+getRepo()+' \"'+ dest+'\"'
  );
}

Didn't think it warranted a pull from my side :)

**Comment by pasqualevitiello** [comment]
Same issue on OSX. If in the destination path there's a folder containing a space, Terminal returns: { [Error: Command failed: Too many arguments.

**Comment by jhopper28** [comment]
@WrathZA Thanks for the fix! It's been merged into the master repo.
