### ISSUE TITLE
Setting hostname (IP) for webpack server

### ISSUE THREAD

**Issue by silasb** [reapp/reapp#6]
I run almost all my code on my local (private) linux box.  I've tried looking through [reapp-pack](https://github.com/reapp/reapp-pack) as suggested in the readme to configure webpack settings, but for the life of my I can't figure out how to assign webpack a IP address that it should be listening on.  Any hints?

**Comment by natew** [comment]
Example usages are here:
https://github.com/reapp/reapp-pack/tree/master/config

Also if you want to avoid using the CLI check out the HN app:
https://github.com/reapp/hacker-news-app/tree/master/config

**Comment by natew** [comment]
Ah, I see what you meant. I read IP as port. Thanks for the PR though!
