### ISSUE TITLE
Unexpected token < You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by jasonshark** [reapp/reapp#65]
I am getting an error from the following code:

```
import { Reapp, React, View } from 'reapp-kit';

var MapView = React.createClass({
  render: function(){
    return (
      <div id="map"><span>Map Would be Here !!</span></div>
    );
  }
});

var Home = React.createClass({
  render: function(){
    return (
        <View title='Where Am I'>
        
          <MapView />
          <MapView />
        </View>
    );
  }
});

export default Reapp(Home);
```

The error I'm getting is: 

```
WARNING in ./app/app.js
Critical dependencies:
7:22-29 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./app/app.js 7:22-29

WARNING in ./app/components/Home.jsx
Module parse failed: /usr/local/lib/node_modules/reapp/node_modules/reapp-pack/node_modules/react-hot-loader/index.js!/usr/local/lib/node_modules/reapp/node_modules/reapp-pack/node_modules/babel-loader/index.js?{"stage": 0, "optional": ["optimisation.react.constantElements", "bluebirdCoroutines"]}!/Users/connorleech/Projects/reapp_maps/app/components/Home.jsx Line 14: Unexpected token <
You may need an appropriate loader to handle this file type.
|   'div',
|   { id: 'map' },
|   <span>Map Would be Here !!</span>
| );
| 
 @ ./app ^\.\/.*$
webpack: bundle is now VALID.
```

**Comment by boazy** [comment]
I've also had this issue right now. This seems to be caused by the `optimisation.react.constantElements` option passed to babel-loader. The best fix I've managed so far is to manually edit `node_modules/reapp-pack/index.js` in the directory where reapp is installed (for me it was `/usr/local/lib/node_modules/reapp` with a global installation) and remove that option.

Search for a line that looks like:

  loader: 'babel-loader?{"stage": 0, "optional": ["optimisation.react.constantElements",   "bluebirdCoroutines"]}',
 
And remove that option to get:

    loader: 'babel-loader?{"stage": 0, "optional": ["bluebirdCoroutines"]}',

Hope that helps, but I'm also waiting for a more permanent fix.

**Comment by natew** [comment]
Went ahead and made that change in pack for now.

On Wed, May 13, 2015 at 2:16 AM, Boaz Yaniv <notifications@github.com>
wrote:

> I've also had this issue right now. This seems to be caused by the
> optimisation.react.constantElements option passed to babel-loader. The
> best fix I've managed so far is to manually edit
> node_modules/reapp-pack/index.js in the directory where reapp is
> installed (for me it was /usr/local/lib/node_modules/reapp with a global
> installation) and remove that option.
>
> Search for a line that looks like:
>
> loader: 'babel-loader?{"stage": 0, "optional":
> ["optimisation.react.constantElements", "bluebirdCoroutines"]}',
>
> And remove that option to get:
>
> loader: 'babel-loader?{"stage": 0, "optional": ["bluebirdCoroutines"]}',
>
> Hope that helps, but I'm also waiting for a more permanent fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/reapp/reapp/issues/65#issuecomment-101585308>.
>



-- 
Nate Wienert
natewienert.com @natebirdman <http://twitter.com/natebirdman>

**Comment by boazy** [comment]
Thanks!

**Comment by jasonshark** [comment]
I didn't even have reapp-pack installed. Installed it with npm and it did not fix the issue

**Comment by boazy** [comment]
@jasonshark That's strange. It's should be installed as part of reapp (inside the `node-modules` folder *inside* the reapp module folder). If you install it in any other place, reapp wouldn't use that version so it's not going to help.

**Comment by jasonshark** [comment]
Heyyyy!! Changing that line work. The path for me is `/usr/local/lib/node_modules/reapp/node_modules/reapp-pack` and modified index.js

**Comment by jasonshark** [comment]
Thank you
