### ISSUE TITLE
Can not run reapp app

### ISSUE THREAD

**Issue by smallg** [reapp/reapp#76]
I used reapp command create demo app project.
````javascript
npm install -g reapp
   reapp new myapp
   cd myapp && reapp run
````

When I run this app use "reapp run", there are some errors:

![image](https://cloud.githubusercontent.com/assets/225962/7905728/3570976a-0850-11e5-83dd-545e100e32c8.png)

**Comment by smallg** [comment]
BTW, my platform is Win 7.

**Comment by iamvdo** [comment]
Same error here. :/
Trying to install missing modules by hand does not resolve the problem.

**Comment by distortia** [comment]
I am also receiving these exact issues on Windows 8.1 on current npm version of reapp.

**Comment by abergs** [comment]
Me too, on Windows 10

**Comment by Sivitas** [comment]
Same error for me, installed all the missing modules manually fixed the webpack build, but navigating to localhost it I get an error

`
Uncaught TypeError: this._processChildContext is not a function
`

**Comment by 0w0** [comment]
After I run with `reapp run -d`, I got some useful messages:
```
Doesn't exist: /usr/local/lib/node_modules/reapp/node_modules/reapp-pack/lib/../node_modules/autoprefixer-core
Error! Make sure you have run npm install in reapp-pack
Doesn't exist: /usr/local/lib/node_modules/reapp/node_modules/reapp-pack/lib/../node_modules/autoprefixer-loader
Error! Make sure you have run npm install in reapp-pack
Doesn't exist: /usr/local/lib/node_modules/reapp/node_modules/reapp-pack/lib/../node_modules/babel
Error! Make sure you have run npm install in reapp-pack
....
....
```

Then after `npm i reapp-pack `, I got it worked. Might these information be helpful :)

**Comment by ryd0rz** [comment]
Resolved with new version of reapp.

Do:
npm uninstall -g reapp
npm install -g reapp
reapp new test-reapp
cd test-reapp
reapp run
