### ISSUE TITLE
Reapp new Error

### ISSUE THREAD

**Issue by lawyu89** [reapp/reapp#78]
Running reapp new projectname causes the following error:

___
Desktop :> reapp new myapp

Creating new reapp folder for: myapp...
Running git clone --depth=1 https://github.com/reapp/starter-default /Users/lyu/Desktop/myapp...
Running git init...
Inserting your name...
Running npm install...

 Error
{ [Error: stderr maxBuffer exceeded.] cmd: '/bin/sh -c npm install' }
___
It still creates the folder and whatnot but I was not able to run the default reapp home page until I updated the reapp-kit version from 1.2.0 to 1.2.15

**Comment by ryd0rz** [comment]
Resolved with new version of reapp.

Do:
npm uninstall -g reapp
npm install -g reapp
reapp new test-reapp
cd test-reapp
reapp run
