### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by ndevr** [reapp/reapp#79]
Is that Project still active?

**Comment by abuisman** [comment]
Which one?

**Comment by jeveloper** [comment]
+1 No updates since May, any particular reason?

**Comment by abuisman** [comment]
@jeveloper 
The original author has announced (in the gitter chat) that he will be phasing out his involvement in the project: 

"By the way everyone I've stared on a new project
reapp was incredible to build, and has tons of promise
if anyone would be interested in taking it over, someone who has worked with it and helped with it, get in touch with me at my email natewienert / gmail"

I have seen some questions pop-up regarding commit permissions and PRs, but he hasn't really answered those.

**Comment by jhopper28** [comment]
@jeveloper 
reapp is still active! Once I get write access from @natew I'll be processing any outstanding PRs.

**Comment by natew** [comment]
@jhopper28 I've added a couple people, I thought I had added you! Will do that now.

**Comment by morenoh149** [comment]
it's alive. This should be closed.
