### ISSUE TITLE
Trouble Getting Builds to Run

### ISSUE THREAD

**Issue by strazi** [reapp/reapp#82]
I am able to install and run the dev server just fine. But when I output a build, all I get is a blank screen when trying to load it.

There are no console errors, and all the files get created, but it doesn't look like anything is getting rendered.

Am I missing something?

**Comment by mbrookes** [comment]
Can you walk us through the exact steps you followed to install and run? What OS are you working from?  What browser are you using? Anything else of consequence?

**Comment by strazi** [comment]
Pretty standard I think:
`npm install -g reapp
reapp new myapp
cd myapp
reapp build`

Running on Mac OS (10.11)
Testing in Chrome 43

I put up the output here:
`http://strazi.org/reapp/`

Only weird thing I'm seeing is a `noscript` element being rendered inside of the app div.

**Comment by mbrookes** [comment]
Pretty sure Chrome is your problem. I believe recent builds break Reapp. Can you try Safari?

**Comment by strazi** [comment]
Safari is showing a meta tag warning, but still blank.

If I do `reapp run` it works in Chrome on localhost just fine. I'm just stuck at getting a build to work.

**Comment by mbrookes** [comment]
Just tried your linked site (sorry, missed that first time round). I see what you mean - hopefully @jhopper28 will be able to help...

**Comment by globexdesigns** [comment]
I have the same problem on Win 7. Here's the output:

```
WARNING in ./app/app.js
Critical dependencies:
7:22-29 require function is used in a way in which dependencies cannot be static
ally extracted
 @ ./app/app.js 7:22-29

ERROR in ./~/reapp-kit/dist/index.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/genera
tor' in D:\Github\afk-reapp\afk\node_modules\reapp-kit\dist
 @ ./~/reapp-kit/dist/index.js 57:17-63

ERROR in ./~/reapp-kit/dist/index.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/render
' in D:\Github\afk-reapp\afk\node_modules\reapp-kit\dist
 @ ./~/reapp-kit/dist/index.js 61:14-57

ERROR in ./~/reapp-kit/dist/lib/Reapp.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/Routed
ViewListMixin' in D:\Github\afk-reapp\afk\node_modules\reapp-kit\dist\lib
 @ ./~/reapp-kit/dist/lib/Reapp.js 4:26-82

ERROR in ./~/reapp-kit/dist/lib/Page.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/Routed
ViewListMixin' in D:\Github\afk-reapp\afk\node_modules\reapp-kit\dist\lib
 @ ./~/reapp-kit/dist/lib/Page.js 27:27-83
webpack: bundle is now VALID.

Note: you have a require warning on your routes, this is ok!
```

**Comment by curist** [comment]
Pretty much the same thing as @globexdesigns 's comment, I just did
 ``` sh
npm install -g reapp
reapp new foo
cd foo && reapp run
```

What I got

``` sh
WARNING in ./app/app.js
Critical dependencies:
7:22-29 require function is used in a way in which dependencies cannot be statically extracted
 @ ./app/app.js 7:22-29

ERROR in ./~/reapp-kit/dist/index.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/generator' in /private/tmp/foo/node_modules/reapp-kit/dist
 @ ./~/reapp-kit/dist/index.js 57:17-63

ERROR in ./~/reapp-kit/dist/index.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/render' in /private/tmp/foo/node_modules/reapp-kit/dist
 @ ./~/reapp-kit/dist/index.js 61:14-57

ERROR in ./~/reapp-kit/dist/lib/Reapp.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/RoutedViewListMixin' in /private/tmp/foo/node_modules/reapp-kit/dist/lib
 @ ./~/reapp-kit/dist/lib/Reapp.js 4:26-82

ERROR in ./~/reapp-kit/dist/lib/Page.js
Module not found: Error: Cannot resolve module 'reapp-routes/react-router/RoutedViewListMixin' in /private/tmp/foo/node_modules/reapp-kit/dist/lib
 @ ./~/reapp-kit/dist/lib/Page.js 27:27-83
webpack: bundle is now VALID.

Note: you have a require warning on your routes, this is ok!
```

**Comment by curist** [comment]
Oh well, it looks like someone forgot to `npm run build` before `npm publish` for `reapp-routes`, so the `reapp-routes` currently contains nothing.

After that issue is resolved, now I got `Uncaught TypeError: this._processChildContext is not a function contextPatch.js:84` in chrome.

**Comment by jhopper28** [comment]
@curist Can you please try again and let me know the results?

**Comment by curist** [comment]
@jhopper28 Glad to report that runs perfectly for me this time!

**Comment by strazi** [comment]
Can you clarify how you fixed it or what changed?
